version: '3.7'
services:
  prod:
    container_name: ixo-feegrant-nest
    image: ghcr.io/ixofoundation/ixo-feegrant-nest:latest
    restart: unless-stopped
    ports:
      - 3000:3000
  dev:
    container_name: ixo-feegrant-nest-dev
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    image: ixo-feegrant-nest:dev
    restart: unless-stopped
    volumes:
      - ./:/app
    ports:
      - 3001:3001
